name: Render R Markdown

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - name: Install packages
      run: R -e 'install.packages(c("rmarkdown", "brms", "tidyverse"))'
    - name: Render report
      run: R -e 'rmarkdown::render("BayesAssignment6.Rmd")'
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: BayesAssignment6.html
